server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    server_tokens off;
    location / { try_files $uri $uri/ =404; }
    location ~ /\. { deny all; }
    location ~* \.(?:css|js|webp|png|jpg|svg|woff2)$ {
        expires 1h;
        add_header Cache-Control "public";
    }
    gzip on;
    gzip_types text/css application/javascript image/svg+xml;
}
